services:
  web-chat:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - web-chat-vol:/usr/local/pgsql/data
volumes:
  web-chat-vol:
    external: true
